services:
  bind9:
    container_name: bind9
    image: ubuntu/bind9
    environment:
      - BIND9_USER=root
      - TZ=America/Winnipeg
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - bind9_config:/etc/bind
      - bind9_cache:/var/cache/bind
      - bind9_records:/var/lib/bind
    restart: unless-stopped
volumes:
  bind9_config:
    name: bind9_config
  bind9_cache:
    name: bind9_cache
  bind9_records:
    name: bind9_records