services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443"
      - "3000:3000/tcp"
    volumes:
      - adguardhome_config:/opt/adguardhome/conf
      - adguardhome_work:/opt/adguardhome/work
    restart: unless-stopped
volumes:
  adguardhome_config:
    name: adguardhome_config
  adguardhome_work:
    name: adguardhome_work