services:
  traefik:
    image: traefik:1.7.6-alpine
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes/traefik_config/_data/traefik.toml:/traefik.toml
      - /var/lib/docker/volumes/traefik_config/_data/acme.json:/acme.json
    networks:
      - web
    restart: unless-stopped
    labels:
      - traefik.frontend.rule=Host:monitor.{Domain_Name}
      - traefik.port=8080
networks:
  web:
    external: true