version: '3'

services:
  reverse-proxy:
    image: traefik:v2.11
    container_name: traefik
    environment:
      - TZ=America/${location}
      - TRAEFIK_ACCESSLOG=true
      - TRAEFIK_ACCESSLOG_FILEPATH=/var/log/traefik/access.log
      #- TRAEFIK_LOG_LEVEL=DEBUG
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_API_DISABLEDASHBOARDAD=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_PROVIDERS_DOCKER_ENDPOINT=tcp://docker-socket-proxy:2375
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
      - TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO=websecure
      - TRAEFIK_ENTRYPOINTS_VPN_ADDRESS=:51820/udp
      - TRAEFIK_CERTIFICATESRESOLVERS_DUCKDNS_ACME_DNSCHALLENGE=true
      - TRAEFIK_CERTIFICATESRESOLVERS_DUCKDNS_ACME_DNSCHALLENGE_DISABLEPROPAGATIONCHECK=true #Not recommended. Helped resolve certificate not getting created issue.
      - TRAEFIK_CERTIFICATESRESOLVERS_DUCKDNS_ACME_DNSCHALLENGE_PROVIDER=duckdns
      - TRAEFIK_CERTIFICATESRESOLVERS_DUCKDNS_ACME_DNSCHALLENGE_RESOLVERS=1.1.1.1
      - TRAEFIK_CERTIFICATESRESOLVERS_DUCKDNS_ACME_EMAIL=${emailaddress}
      - TRAEFIK_CERTIFICATESRESOLVERS_DUCKDNS_ACME_STORAGE=/letsencrypt/acme.json
      - DUCKDNS_TOKEN=${duckdnstoken}
      - TRAEFIK_EXPERIMENTAL_PLUGINS_BOUNCER_MODULENAME=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      - TRAEFIK_EXPERIMENTAL_PLUGINS_BOUNCER_VERSION=v1.2.1-rc1
      - TRAEFIK_EXPERIMENTAL_PLUGINS_GOOGLEOAUTH_MODULENAME=github.com/andrewkroh/google-oidc-auth-middleware
      - TRAEFIK_EXPERIMENTAL_PLUGINS_GOOGLEOAUTH_VERSION=v0.0.4
      - TRAEFIK_EXPERIMENTAL_PLUGINS_GEOBLOCK_MODULENAME=github.com/PascalMinder/geoblock
      - TRAEFIK_EXPERIMENTAL_PLUGINS_GEOBLOCK_VERSION=v0.2.7
    labels:
      - "traefik.enable=true"
      #- "traefik.docker.network=${traefik_connected_network}"
      - "traefik.http.routers.traefik.rule=Host(`${domainurlrule}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=duckdns"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=geoblock-traefik@docker,crowdsec-traefik@docker,googleoauth-traefik@docker"
      - "traefik.http.middlewares.geoblock-traefik.plugin.geoblock.allowLocalRequests=true"
      - "traefik.http.middlewares.geoblock-traefik.plugin.geoblock.allowUnknownCountries=false"
      - "traefik.http.middlewares.geoblock-traefik.plugin.geoblock.api=https://get.geojs.io/v1/ip/country/{ip}"
      - "traefik.http.middlewares.geoblock-traefik.plugin.geoblock.apiTimeoutMs=150"
      - "traefik.http.middlewares.geoblock-traefik.plugin.geoblock.cacheSize=15"
      - "traefik.http.middlewares.geoblock-traefik.plugin.geoblock.countries=CA"
      - "traefik.http.middlewares.geoblock-traefik.plugin.geoblock.forceMonthlyUpdate=true"
      - "traefik.http.middlewares.geoblock-traefik.plugin.geoblock.logAllowedRequests=true"
      - "traefik.http.middlewares.geoblock-traefik.plugin.geoblock.logApiRequests=true"
      - "traefik.http.middlewares.geoblock-traefik.plugin.geoblock.logLocalRequests=true"
      - "traefik.http.middlewares.geoblock-traefik.plugin.geoblock.silentStartUp=false"
      - "traefik.http.middlewares.geoblock-traefik.plugin.geoblock.unknownCountryApiResponse=nil"
      #- "traefik.http.middlewares.geoblock-traefik.plugin.geoblock.allowedIPAddresses=${IPaddresses}"
      - "traefik.http.middlewares.crowdsec-traefik.plugin.bouncer.enabled=true"
      #- "traefik.http.middlewares.crowdsec-traefik.plugin.bouncer.LogLevel=DEBUG"
      - "traefik.http.middlewares.crowdsec-traefik.plugin.bouncer.CrowdsecMode=live"
      - "traefik.http.middlewares.crowdsec-traefik.plugin.bouncer.crowdseclapikey=${crowdseclapikey}"
      - "traefik.http.middlewares.googleoauth-traefik.plugin.googleoauth.oidc.clientID=${oauth_clientid}"
      - "traefik.http.middlewares.googleoauth-traefik.plugin.googleoauth.oidc.clientsecret=${oauth_clientsecret}"
      - "traefik.http.middlewares.googleoauth-traefik.plugin.googleoauth.cookie.name=${custom_cookie_name}"
      - "traefik.http.middlewares.googleoauth-traefik.plugin.googleoauth.cookie.secret=${hmac_key}"
      - "traefik.http.middlewares.googleoauth-traefik.plugin.googleoauth.authorized.emails=${authorized_emails}"
      - "traefik.http.middlewares.googleoauth-traefik.plugin.googleoauth.authorized.domains=${authorized_domains}"
      #- "traefik.http.middlewares.googleoauth-traefik.plugin.googleoauth.debug=true"
    ports:
      - 80:80
      - 443:443
      - 51820:51820/udp
      - 8080:8080
    networks:
      - reverse.proxy-crowdsec
      - reverse.proxy-homeassistant
      - reverse.proxy-wireguard
      - docker-socket-proxy
      - testing-external
    volumes:
      - traefik_logs:/var/log/traefik
      - traefik_letsencrypt:/letsencrypt
    restart: unless-stopped
    depends_on:
      - crowdsec
      - docker-socket-proxy

  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.0-1
    container_name: crowdsec
    environment:
      - TZ=America/${location}
      - COLLECTIONS=crowdsecurity/traefik
      - CUSTOM_HOSTNAME=crowdsec
      - BOUNCER_KEY_TRAEFIK=${crowdseclapikey}
    networks:
      - reverse.proxy-crowdsec
    volumes:
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - traefik_logs:/var/log/traefik:ro
      - crowdsec_db:/var/lib/crowdsec/data/
      - crowdsec_config:/etc/crowdsec/
    labels:
      - traefik.enable=false
    restart: unless-stopped

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:edge
    container_name: docker-socket-proxy
    environment:
      - TZ=America/${location}
      # Access granted by default:
      - EVENTS=1
      - PING=1
      - VERSION=1
      # Access revoked by default:
      # Security-critical
      - AUTH=0
      - SECRETS=0
      - POST=0
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=0
      - INFO=0
      - NETWORKS=0
      - NODES=0
      - PLUGINS=0
      - SERVICES=0
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=0
      - VOLUMES=0
    ports:
      - 127.0.0.1:2375:2375
    networks:
      - docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=false
    restart: unless-stopped

volumes:
  traefik_logs:
    name: traefik_logs
  traefik_letsencrypt:
    name: traefik_letsencrypt
  crowdsec_db:
    name: crowdsec_db
  crowdsec_config:
    name: crowdsec_config

networks:
  reverse.proxy-crowdsec:
    name: reverse.proxy-crowdsec
  reverse.proxy-homeassistant:
    name: reverse.proxy-homeassistant
  reverse.proxy-wireguard:
    name: reverse.proxy-wireguard
  docker-socket-proxy:
    name: docker-socket-proxy
  testing-external:
    name: testing-external