version: '3'

services:
  reverse-proxy:
    image: traefik:v2.11
    container_name: traefik
    environment:
      - TZ=America/Winnipeg
      - TRAEFIK_ACCESSLOG=true
      - TRAEFIK_ACCESSLOG_FILEPATH=/var/log/traefik/access.log
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_API_INSECURE=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_PROVIDERS_DOCKER_ENDPOINT=tcp://docker-socket-proxy:2375
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
      - TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO=websecure
      - TRAEFIK_CERTIFICATESRESOLVERS_DUCKDNS_ACME_DNSCHALLENGE=true
      - TRAEFIK_CERTIFICATESRESOLVERS_DUCKDNS_ACME_DNSCHALLENGE_PROVIDER=duckdns
      - TRAEFIK_CERTIFICATESRESOLVERS_DUCKDNS_ACME_EMAIL=${emailaddress}
      - TRAEFIK_CERTIFICATESRESOLVERS_DUCKDNS_ACME_STORAGE=/letsencrypt/acme.json
      - DUCKDNS_TOKEN=${duckdnstoken}
      - TRAEFIK_EXPERIMENTAL_PLUGINS_BOUNCER_MODULENAME=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      - TRAEFIK_EXPERIMENTAL_PLUGINS_BOUNCER_VERSION=v1.2.1-rc1
      - TRAEFIK_EXPERIMENTAL_PLUGINS_GOOGLEOAUTH_MODULENAME=github.com/andrewkroh/google-oidc-auth-middleware
      - TRAEFIK_EXPERIMENTAL_PLUGINS_GOOGLEOAUTH_VERSION=v0.0.4
      - TRAEFIK_EXPERIMENTAL_PLUGINS_GEOBLOCK_MODULENAME=github.com/PascalMinder/geoblock
      - TRAEFIK_EXPERIMENTAL_PLUGINS_GEOBLOCK_VERSION=v0.2.7
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - reverse.proxy-crowdsec
      - docker-socket-proxy
      - testing-external
    volumes:
      - traefik_logs:/var/log/traefik
      - traefik_letsencrypt:/letsencrypt
    restart: unless-stopped
    depends_on:
      - crowdsec
      - docker-socket-proxy

  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.0-1
    container_name: crowdsec
    environment:
      - TZ=America/Winnipeg
      - COLLECTIONS=crowdsecurity/traefik
      - CUSTOM_HOSTNAME=crowdsec
      - BOUNCER_KEY_TRAEFIK=${crowdseclapikey}
    networks:
      - reverse.proxy-crowdsec
    volumes:
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - traefik_logs:/var/log/traefik:ro
      - crowdsec_db:/var/lib/crowdsec/data/
      - crowdsec_config:/etc/crowdsec/
    labels:
      - traefik.enable=false
    restart: unless-stopped

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:edge
    container_name: docker-socket-proxy
    environment:
      - TZ=America/Winnipeg
      # Access granted by default:
      - EVENTS=1
      - PING=1
      - VERSION=1
      # Access revoked by default:
      # Security-critical
      - AUTH=0
      - SECRETS=0
      - POST=0
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=0
      - INFO=0
      - NETWORKS=0
      - NODES=0
      - PLUGINS=0
      - SERVICES=0
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=0
      - VOLUMES=0
    ports:
      - 127.0.0.1:2375:2375
    networks:
      - docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=false
    restart: unless-stopped

volumes:
  traefik_logs:
    name: traefik_logs
  traefik_letsencrypt:
    name: traefik_letsencrypt
  crowdsec_db:
    name: crowdsec_db
  crowdsec_config:
    name: crowdsec_config

networks:
  reverse.proxy-crowdsec:
    name: reverse.proxy-crowdsec
  docker-socket-proxy:
    name: docker-socket-proxy
  testing-external:
    name: testing-external