version: '3'

services:
  whoami_test:
    image: "traefik/whoami"
    container_name: "simple-service-test"
    networks:
      - testing-internal
      - testing-external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test.rule=Host(`${domainurlrule}`)"
      - "traefik.http.routers.test.entrypoints=websecure"
      - "traefik.http.routers.test.tls.certresolver=duckdns"
      - "traefik.http.routers.test.middlewares=crowdsec-test@docker"
      - "traefik.http.middlewares.crowdsec-test.plugin.bouncer.enabled=true"
      #- "traefik.http.middlewares.crowdsec-test.plugin.bouncer.LogLevel=DEBUG"
      - "traefik.http.middlewares.crowdsec-test.plugin.bouncer.CrowdsecMode=live"
      - "traefik.http.middlewares.crowdsec-test.plugin.bouncer.crowdseclapikey=${crowdseclapikey}"

networks:
  testing-internal:
    name: testing-internal
  testing-external:
    name: testing-external