version: '3'
services:
  homeassistant:
    image: "homeassistant/home-assistant:stable"
    container_name: home-assistant
    environment:
      - TZ=America/${location}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${traefik_connected_network}"
      - "traefik.http.routers.homeassistant.rule=Host(`${domainurlrule}`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls.certresolver=duckdns"
      - "traefik.http.routers.homeassistant.middlewares=geoblock-homeassistant@docker,crowdsec-homeassistant@docker,googleoauth-homeassistant@docker"
      - "traefik.http.middlewares.geoblock-homeassistant.plugin.geoblock.allowLocalRequests=false"
      - "traefik.http.middlewares.geoblock-homeassistant.plugin.geoblock.allowUnknownCountries=false"
      - "traefik.http.middlewares.geoblock-homeassistant.plugin.geoblock.api=https://get.geojs.io/v1/ip/country/{ip}"
      - "traefik.http.middlewares.geoblock-homeassistant.plugin.geoblock.apiTimeoutMs=150"
      - "traefik.http.middlewares.geoblock-homeassistant.plugin.geoblock.cacheSize=15"
      - "traefik.http.middlewares.geoblock-homeassistant.plugin.geoblock.countries=CA"
      - "traefik.http.middlewares.geoblock-homeassistant.plugin.geoblock.forceMonthlyUpdate=true"
      - "traefik.http.middlewares.geoblock-homeassistant.plugin.geoblock.logAllowedRequests=true"
      - "traefik.http.middlewares.geoblock-homeassistant.plugin.geoblock.logApiRequests=true"
      - "traefik.http.middlewares.geoblock-homeassistant.plugin.geoblock.logLocalRequests=true"
      - "traefik.http.middlewares.geoblock-homeassistant.plugin.geoblock.silentStartUp=false"
      - "traefik.http.middlewares.geoblock-homeassistant.plugin.geoblock.unknownCountryApiResponse=nil"
      #- "traefik.http.middlewares.geoblock-homeassistant.plugin.geoblock.allowedIPAddresses=${IPaddresses}"
      - "traefik.http.middlewares.crowdsec-homeassistant.plugin.bouncer.enabled=true"
      #- "traefik.http.middlewares.crowdsec-homeassistant.plugin.bouncer.LogLevel=DEBUG"
      - "traefik.http.middlewares.crowdsec-homeassistant.plugin.bouncer.CrowdsecMode=live"
      - "traefik.http.middlewares.crowdsec-homeassistant.plugin.bouncer.crowdseclapikey=${crowdseclapikey}"
      - "traefik.http.middlewares.googleoauth-homeassistant.plugin.googleoauth.oidc.clientID=${oauth_clientid}"
      - "traefik.http.middlewares.googleoauth-homeassistant.plugin.googleoauth.oidc.clientsecret=${oauth_clientsecret}"
      - "traefik.http.middlewares.googleoauth-homeassistant.plugin.googleoauth.cookie.name=${custom_cookie_name}"
      - "traefik.http.middlewares.googleoauth-homeassistant.plugin.googleoauth.cookie.secret=${hmac_key}"
      - "traefik.http.middlewares.googleoauth-homeassistant.plugin.googleoauth.authorized.emails=${authorized_emails}"
      - "traefik.http.middlewares.googleoauth-homeassistant.plugin.googleoauth.authorized.domains=${authorized_domains}"
      #- "traefik.http.middlewares.googleoauth-homeassistant.plugin.googleoauth.debug=true"
    ports:
      - "8123:8123/tcp"
    networks:
      - reverse.proxy-homeassistant
      - home.assistant-zwave
      - home.assistant-mdns.reflector
      - home.assistant-mosquitto
    volumes:
      - home-assistant_config:/config
    restart: unless-stopped
    depends_on:
      - zwave-js-ui
      - mdns-reflector
      - mosquitto

  zwave-js-ui:
    image: zwavejs/zwave-js-ui:latest
    container_name: zwave-js-ui
    environment:
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=America/${location}
    ports:
      - '8091:8091' # port for web interface
      - '127.0.0.1:3000:3000' # port for Z-Wave JS websocket server
    networks:
      - home.assistant-zwave
    volumes:
      - zwave_config:/usr/src/app/store
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    devices:
      - '/dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00:/dev/zwave'

  mdns-reflector:
    image: flungo/avahi
    container_name: mdns-reflector
    environment:
      - REFLECTOR_ENABLE_REFLECTOR=yes
    networks:
      - physical-macvlan
      - home.assistant-mdns.reflector
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    ports:
      - "127.0.0.1:1883:1883" #listener
    networks:
      - home.assistant-mosquitto
      - mosquitto-govee.mqtt
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped

  govee-mqtt:
    image: ghcr.io/wez/govee2mqtt:latest
    container_name: govee-mqtt
    environment:
      - GOVEE_EMAIL=
      - GOVEE_PASSWORD=
      - GOVEE_API_KEY=
      - GOVEE_MQTT_HOST=
      - GOVEE_MQTT_PORT=1883
      - GOVEE_TEMPERATURE_SCALE=C
      - RUST_LOG_STYLE=always
      #- RUST_LOG=govee=trace
      - TZ=America/${location}
    networks:
      - mosquitto-govee.mqtt
    restart: unless-stopped

volumes:
  home-assistant_config:
    name: home-assistant_config
  zwave_config:
    name: zwave_config
  mosquitto_config:
    name: mosquitto_config
  mosquitto_data:
    name: mosquitto_data
  mosquitto_log:
    name: mosquitto_log

networks:
  reverse.proxy-homeassistant:
    name: reverse.proxy-homeassistant
  home.assistant-zwave:
    name: home.assistant-zwave
  home.assistant-mdns.reflector:
    name: home.assistant-mdns.reflector
  physical-macvlan:
    #Must create this network manually with CLI:
    #Change IP structure to match the LAN it's connecting to (same as dockers physical LAN). Also change parent=eno1 to docker hosts physical adapter in the command below:
    #docker network create -d macvlan --subnet=192.168.X.0/24 --ip-range=192.168.X.8/29 --gateway=192.168.X.1 -o parent=eno1 physical-macvlan
    name: physical-macvlan
    external: true
  home.assistant-mosquitto:
    name: home.assistant-mosquitto
  mosquitto-govee.mqtt:
    name: mosquitto-govee.mqtt