services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - jellyfin_media:/media
    environment:
      - JELLYFIN_PublishedServerUrl=${autodiscoveryDomain/IP}
      - TZ=America/Winnipeg
    ports:
      - 8096:8096 #http webUI
      - 8920:8920 #https webUI
      - 7359:7359/udp #local network discovery
      - 1900:1900/udp #DNLA service discovery
    restart: 'unless-stopped'
volumes:
  jellyfin_config:
    name: jellyfin_config
  jellyfin_cache:
    name: jellyfin_cache
  jellyfin_media:
    name: jellyfin_media