services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    environment:
      - TZ=America/${location}
      - FRIGATE_RTSP_PASSWORD="password"
    labels:
      - "traefik.enable=false"
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    volumes:
      - frigate_config:/config
      - frigate_media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    restart: unless-stopped
    shm_size: "64mb"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

volumes:
  frigate_config:
    name: frigate_config
  frigate_media:
    name: frigate_media